/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c1_Object.h"
#include "c31_PictureMotionCounterpart.h"


/*
 * call analyse 0 c31_PictureMotionCounterpart_m1__init_
 */
/* dmec/Picture.<init>()V */

void c31_PictureMotionCounterpart_m1__init_(object_t* obj0) {

	
/*==============================================================/
| 5: null
/==============================================================*/
	KESO_CHECK_NULLPOINTER(obj0,"<init>",1);
	c1_Object_m1__init_((object_t*)obj0);
	/* goto c31_PictureMotionCounterpart_m1__init__B6 */;
	
/* c31_PictureMotionCounterpart_m1__init__B6:  Pred:  0 No: 2 done */
	return;
}

