/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c12_String.h"


/*
 * call analyse 0 c12_String_m6__init_
 */
/* java/lang/String.<init>()V */

void c12_String_m6__init_(object_t* obj0) {
	object_t* obj1_0;

	
/*==============================================================/
| 25: 		value = NULL;
| 26: 	}
/==============================================================*/
	obj1_0 = ((object_t*)SC12_STRING_C12F2_NULL);
	KESO_CHECK_NULLPOINTER(obj0,"<init>",8);
	KESO_WRBR((C12_STRING_OBJ(obj0)->c12f1_value),obj1_0);
	/* goto c12_String_m6__init__B13 */;
	
/* c12_String_m6__init__B13:  Pred:  0 No: 2 done */
	return;
}

