/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c1_Object.h"


/*
 * call analyse 0 c1_Object_m1__init_
 */
/* java/lang/Object.<init>()V */

void c1_Object_m1__init_(object_t* obj0) {

	
/*==============================================================/
| 17: public class Object {
/==============================================================*/
	/* goto c1_Object_m1__init__B2 */;
	
/* c1_Object_m1__init__B2:  Pred:  0 No: 2 done */
	return;
}

