function plot_memory(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 11-Feb-2010 16:15:24

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'No CSMA-CA/ACK','No ACK','No CSMA-CA','Full','Full/Beacon-enabled'},...
    'XTick',[1 2 3 4 5],...
    'FontSize',11);
box('on');
hold('all');

% Create ylabel
ylabel('Segment size (bytes)','FontWeight','demi','FontSize',12);

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'BarWidth',0.6,'BarLayout','stacked','Parent',axes1);
set(bar1(1),'FaceColor',[0 0 1],'DisplayName','Code');
set(bar1(2),'FaceColor',[0 0.5 0],'DisplayName','Data');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 1 1],'Location','NorthWest','YColor',[1 1 1],...
    'XColor',[1 1 1],...
    'FontSize',12);

