function plot_energy(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-Feb-2010 18:01:11

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'XTickLabel',{'2','3','4','5'},...
    'XTick',[1 2 3 4],...
    'FontSize',11);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'MarkerSize',10,'LineWidth',2);
set(plot1(1),'Marker','o','DisplayName','No CSMA-CA / ACK');
set(plot1(2),'Marker','square','DisplayName','No ACK');
set(plot1(3),'Marker','x','DisplayName','No CSMA-CA');
set(plot1(4),'Marker','.','DisplayName','CSMA-CA/ACK enabled');
set(plot1(5),'Marker','+','DisplayName','CSMA-CA/ACK/beacons enabled');

% Create xlabel
xlabel('Number of nodes','FontWeight','demi','FontSize',12);

% Create ylabel
ylabel('Energy per byte (joules)','FontWeight','demi','FontSize',12);

% Create legend
legend(axes1,'show');

