/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: keso/core/NonCopyable */

#ifndef __i14_NonCopyable_H__
#define __i14_NonCopyable_H__ 1
#include <keso_types.h>

#define I14_NONCOPYABLE_ID ((class_id_t)14)
#define I14_NONCOPYABLE_OBJ(_obj_) ((i14_NonCopyable_t*)(_obj_))
#define CHK_IFACE_ID14(_obj_) keso_checkiface(_obj_,1)
#define INSTANCEOF_IFACE_ID14(_obj_) keso_instanceof_iface(_obj_,1)

/* class methods prototypes */

/* object data */
typedef struct {
/* i14_NonCopyable */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* i14_NonCopyable */
} i14_NonCopyable_t;

#endif

