function plot_coef_ppc_hw(n_blocks1, YMatrix1)
%CREATEFIGURE(N_BLOCKS1,YMATRIX1)
%  N_BLOCKS1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 05-Mar-2010 15:22:22

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12);
% Uncomment the following line to preserve the X-limits of the axes
xlim([1 16]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim([0 0.008]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(n_blocks1,YMatrix1,'Parent',axes1,'MarkerSize',10,...
    'LineWidth',1.75);
set(plot1(1),'Marker','o','Color',[0.8471 0.1608 0],...
    'DisplayName','Blocks in serial (SW)');
set(plot1(2),'Marker','square','Color',[0.07843 0.1686 0.549],...
    'DisplayName','Blocks in parallel (SW)');
set(plot1(3),'Marker','x','Color',[0.1686 0.5059 0.3373],...
    'DisplayName','Blocks with multiple in/out (SW)');
set(plot1(4),'Marker','o','LineStyle','--','Color',[0.8471 0.1608 0],...
    'DisplayName','Blocks in serial (HW)');
set(plot1(5),'Marker','square','LineStyle','--',...
    'Color',[0.07843 0.1686 0.549],...
    'DisplayName','Blocks in parallel (HW)');
set(plot1(6),'Marker','x','LineStyle','--','Color',[0.1686 0.5059 0.3373],...
    'DisplayName','Blocks with multiple in/out (SW)');

% Create xlabel
xlabel({'Number of blocks/inputs/outputs',''},'FontSize',12);

% Create ylabel
ylabel('Coefficient of variation','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest');

