/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: java/lang/RuntimeException */

#ifndef __c10_RuntimeException_H__
#define __c10_RuntimeException_H__ 1
#include <keso_types.h>

#define C10_RUNTIMEEXCEPTION_ID ((class_id_t)10)
#define C10_RUNTIMEEXCEPTION_OBJ(_obj_) ((c10_RuntimeException_t*)((object_t**)(_obj_)-1))

/* class methods prototypes */
/* <init>()V */
void c10_RuntimeException_m1__init_(object_t* obj0) __attribute__ ((const)) ;

/* object data */
typedef struct {
/* c10_RuntimeException */
/* c9_Throwable */
	object_t* c9f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c9_Throwable */
/* c10_RuntimeException */
} c10_RuntimeException_t;

#endif

