/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c10_RuntimeException.h"


/*
 * call analyse 0 c10_RuntimeException_m1__init_
 */
/* java/lang/RuntimeException.<init>()V PURE CONST */

void c10_RuntimeException_m1__init_(object_t* obj0) {

	
/*==============================================================/
| 21: 	}
/==============================================================*/
	/* goto c10_RuntimeException_m1__init__B6 */;
	
/* c10_RuntimeException_m1__init__B6:  Pred:  0 No: 2 done */
	return;
}

