/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c12_String.h"
#include "char_array.h"


/*
 * call analyse 0 c12_String_m2_getChars
 */
/* java/lang/String.getChars(II[CI)V */

void c12_String_m2_getChars(object_t* obj0,jint i1,jint i2,object_t* obj3,jint i4) {
	jint i14_0;
	jint i6_1;
	jint i8_1;
	jint i10_1;
	object_t* obj5_0;
	object_t* obj11_0;
	jchar c12_1;

	
/*==============================================================/
| 132: 		if ((srcBegin < 0)
/==============================================================*/
	if (i1<0x0) goto c12_String_m2_getChars_B29;
	
/* c12_String_m2_getChars_B4:  Pred:  0 No: 2 done */
	KESO_CHECK_NULLPOINTER(obj0,"getChars",6);
	obj5_0 = (C12_STRING_OBJ(obj0)->c12f1_value);
	KESO_CHECK_NULLPOINTER(obj5_0,"getChars",9);
	if (i2>((array_t*)obj5_0)->size) goto c12_String_m2_getChars_B29;
	
/* c12_String_m2_getChars_B13:  Pred:  4 No: 3 done */
	if (i2<i1) goto c12_String_m2_getChars_B29;
	
/* c12_String_m2_getChars_B18:  Pred:  13 No: 4 done */
	KESO_CHECK_NULLPOINTER(obj3,"getChars",19);
	if (((array_t*)obj3)->size>=((i2-i1)+i4)) goto c12_String_m2_getChars_B34;
	
c12_String_m2_getChars_B29: /* Pred:  0 4 13 18 No: 5 done */
	
/*==============================================================/
: 133: 				|| (srcEnd > value.length)
: 134: 				|| (srcEnd < srcBegin)
: 135: 				|| (dst.length < (srcEnd - srcBegin + dstBegin)))
| 136: 			throw out_of_bounds();
/==============================================================*/
	while (1) { __asm__ __volatile__ ("nop"); };
	
c12_String_m2_getChars_B34: /* Pred:  18 No: 6 done */
	
/*==============================================================/
| 137: 		charArrayCopy(value, srcBegin, dst, dstBegin, srcEnd - srcBegin);
/==============================================================*/
	obj11_0 = (C12_STRING_OBJ(obj0)->c12f1_value);
	i14_0 = (i2-i1);
	i6_1 = 0x0;
	
cc29103856_c12_String_m4_charArrayCopy_B3: /* Pred:  34 10 No: 7 done */
	/* i6_1 = Phi(0,i6_1)  */;
	if (i6_1>=i14_0) goto cc27182317_c12_String_m4_charArrayCopy_B28;
	
/* cc23103355_c12_String_m4_charArrayCopy_B10:  Pred:  3 No: 8 done */
	i8_1 = (i4+i6_1);
	i10_1 = (i1+i6_1);
	KESO_CHECK_ARR_REF(obj11_0,i10_1,"getChars",45);
	c12_1 = ((char_array_t*)obj11_0)->data[i10_1];
	KESO_CHECK_ARRAY(obj3,i8_1,"getChars",45);
	((char_array_t*)obj3)->data[i8_1]=c12_1;
	i6_1 = (i6_1+0x1);
	goto cc29103856_c12_String_m4_charArrayCopy_B3;
	
cc27182317_c12_String_m4_charArrayCopy_B28: /* Pred:  3 No: 9 done */
	
/*==============================================================/
| 138: 	}
/==============================================================*/
	/* goto c12_String_m2_getChars_B50 */;
	
/* c12_String_m2_getChars_B50:  Pred:  28 No: 10 done */
	return;
}

