/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c12_String.h"


/*
 * call analyse 0 c12_String_m1_length
 */
/* java/lang/String.length()I PURE */

jint c12_String_m1_length(object_t* obj0) {
	jint i1_0;
	object_t* obj2_0;

	
/*==============================================================/
| 122: 		return value.length;
/==============================================================*/
	KESO_CHECK_NULLPOINTER(obj0,"length",1);
	obj2_0 = (C12_STRING_OBJ(obj0)->c12f1_value);
	KESO_CHECK_NULLPOINTER(obj2_0,"length",4);
	i1_0 = ((array_t*)obj2_0)->size;
	/* goto c12_String_m1_length_B7 */;
	
/* c12_String_m1_length_B7:  Pred:  0 No: 2 done */
	return i1_0;
}

