/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: java/lang/String */

#ifndef __c12_String_H__
#define __c12_String_H__ 1
#include <keso_types.h>

#define C12_STRING_ID ((class_id_t)12)
#define C12_STRING_OBJ(_obj_) ((c12_String_t*)((object_t**)(_obj_)-1))

/* class methods prototypes */
/* getChars(II[CI)V */
void c12_String_m2_getChars(object_t* obj0,jint i1,jint i2,object_t* obj3,jint i4);
/* charArrayCopy([CI[CII)V */
void c12_String_m4_charArrayCopy(object_t* obj0,jint i1,object_t* obj2,jint i3,jint i4);
/* <clinit>()V */
void c12_String_m5__clinit_(void);
/* out_of_bounds()Ljava/lang/StringIndexOutOfBoundsException; */
object_t* c12_String_m3_out_of_bounds(object_t* obj0);
/* length()I */
jint c12_String_m1_length(object_t* obj0) __attribute__ ((pure)) ;
/* <init>()V */
void c12_String_m6__init_(object_t* obj0);

/* object data */
typedef struct {
/* c12_String */
	object_t* c12f1_value;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c12_String */
} c12_String_t;

#endif

