/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c12_String.h"
#include "char_array.h"


/*
 * call analyse 1 c12_String_m5__clinit_
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* java/lang/String.<clinit>()V */

void c12_String_m5__clinit_(void) {

	
/*==============================================================/
| 21: 	final private static char[] NULL = new char[0];
/==============================================================*/
	SC12_STRING_C12F2_NULL = (object_t*)keso_alloc_char_array(0x0);
	/* goto c12_String_m5__clinit__B8 */;
	
/* c12_String_m5__clinit__B8:  Pred:  0 No: 2 done */
	return;
}

