/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"
#include "c13_DebugOut.h"


/*
 * call analyse 1 c13_DebugOut_m3__clinit_
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* test/DebugOut.<clinit>()V */
static c6_StringBuffer_t HEAP_SECTION c13_DebugOut_m3__clinit__0={
.class_id=C6_STRINGBUFFER_ID, .gcinfo=1
};

void c13_DebugOut_m3__clinit_(void) {
	jint i3_0;
	object_t* obj0_0;
	object_t* obj4_0;

	
/*==============================================================/
| 8: 	private final static StringBuffer buf = new StringBuffer();
/==============================================================*/
	obj0_0 = ((object_t*) ((object_t**) &c13_DebugOut_m3__clinit__0+1));
	i3_0 = 0x8;
	obj4_0 = keso_alloc_char_array(i3_0);
	(C6_STRINGBUFFER_OBJ(obj0_0)->c6f1_data) = (object_t*)obj4_0;
	(C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length) = 0x0;
	SC13_DEBUGOUT_C13F1_BUF = (object_t*)obj0_0;
	/* goto c13_DebugOut_m3__clinit__B12 */;
	
/* c13_DebugOut_m3__clinit__B12:  Pred:  0 No: 2 done */
	return;
}

