/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: keso/core/Task */

#ifndef __c3_Task_H__
#define __c3_Task_H__ 1
#include <keso_types.h>

#define C3_TASK_ID ((class_id_t)3)
#define C3_TASK_OBJ(_obj_) ((c3_Task_t*)(_obj_))

/* class methods prototypes */
/* <clinit>()V */
void c3_Task_m2__clinit_(void);
/* <init>()V */
void c3_Task_m1__init_(object_t* obj0);

/* object data */
typedef struct {
/* c3_Task */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
	jbyte _domain_id;
	jbyte _e_domain_id;
	jbyte _task_id;
/* c3_Task */
} c3_Task_t;

#endif

