/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c3_Task.h"


/*
 * call analyse 1 c3_Task_m2__clinit_
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* keso/core/Task.<clinit>()V */

void c3_Task_m2__clinit_(void) {

	
/*==============================================================/
| 25: 	public static final Task INVALID_TASK = null;
/==============================================================*/
	/* goto c3_Task_m2__clinit__B6 */;
	
/* c3_Task_m2__clinit__B6:  Pred:  0 No: 2 done */
	return;
}

