/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c7_NativeTestSupport.h"
#include "c4_DmecApp.h"
#include "c13_DebugOut.h"
#include "c5_PictureMotionEstimator.h"

#include "c31_PictureMotionCounterpart.h" /* For time measurements */

#include <c_chronometer.h>  /* For time measurements */
#include <utility/tracer_c.h>


#define MEASURE_TIME 0 /* If you want to measure time overhead you may like to 
                        disable the ME computation (see DUMMY_ME at traits.h) */

/*
 * call analyse 1 c4_DmecApp_m1_launch
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* dmec_app/DmecApp.launch()V */

# if MEASURE_TIME
void* chrono; /* For time measurements */
#endif

#if MEASURE_TIME
#define ITERATIONS 1000000

#else
#define ITERATIONS 1

#endif

void c4_DmecApp_m1_launch(object_t* obj0) {
	object_t* obj7_0;
	object_t* obj4_0;
	object_t* obj5_0;
	object_t* obj6_0;

	
/*==============================================================/
| 20:         DebugOut.println("DMEC APP for KESO is alive!");
: 23:         int pictureHeight = 144;
: 24:         
: 25:         PictureMotionEstimator pme;
| 26:         pme = new PictureMotionEstimator(pictureWidth, pictureHeight, 1);
: 27:         
| 28:         Picture currentPicture = NativeTestSupport.createPicture(pictureWidth, pictureHeight, 0);
| 29:         Picture referencePicture = NativeTestSupport.createPicture(pictureWidth, pictureHeight, 1);
: 30:         
: 31:         PictureMotionCounterpart pmc;        
| 32:         pmc = pme.match(currentPicture, referencePicture);
: 33:         
| 34:         NativeTestSupport.testPictureMotionCounterpart(pmc, pictureWidth, pictureHeight, currentPicture, referencePicture);
: 35:         
| 36:         DebugOut.println("done: OK");
| 37:     }
/==============================================================*/

#if MEASURE_TIME
    chrono = newChronometer(); /* For time measurements */
#endif

    tracer_trace("\nBEGIN: DmecApp::launch\n");

	c13_DebugOut_m1_println((object_t*)((object_t*) ((object_t**) &str0+1)));
	obj7_0 = KESO_ALLOC(C5_PICTUREMOTIONESTIMATOR_ID,sizeof(c5_PictureMotionEstimator_t),0);
	c5_PictureMotionEstimator_m2__init_((object_t*)obj7_0,0xb0,0x90,0x1);
	obj4_0 = c7_NativeTestSupport_m1_createPicture(0xb0,0x90,0x0);
	obj5_0 = c7_NativeTestSupport_m1_createPicture(0xb0,0x90,0x1);
	
	tracer_trace("\nJava will call match\n");
    int i;
#if MEASURE_TIME
    chronometer_start(chrono);
#endif
    for (i = 0; i < ITERATIONS; i++) {
	    obj6_0 = c5_PictureMotionEstimator_m1_match((object_t*)obj7_0,(object_t*)obj4_0,(object_t*)obj5_0);
    }
#if MEASURE_TIME
    chronometer_stop(chrono);
#endif
	tracer_trace("\nJava called match succefully\n");
	
# if MEASURE_TIME
	tracer_trace_s_ulong_s("match (* 1M times) took: ", chronometer_read(chrono), " micro seconds\n");
#endif
	
	if (((c31_PictureMotionCounterpart_t*) obj6_0)->__inner) {
	
	    c7_NativeTestSupport_m2_testPictureMotionCounterpart((object_t*)obj6_0,0xb0,0x90,(object_t*)obj4_0,(object_t*)obj5_0);
	
	    tracer_trace("::::::::::::::::::: MOTION ESTIMATION COMPUTED ALL RIGHT! :::::::::::::::::::\n");
	}
	else {
	    tracer_trace("::::::::::::::::::: NOT COMPUTING ME, JUST MEASURING TIME! :::::::::::::::::::\n");
	}
	
	
	c13_DebugOut_m1_println((object_t*)((object_t*) ((object_t**) &str1+1)));
	/* goto c4_DmecApp_m1_launch_B68 */;
	
/* c4_DmecApp_m1_launch_B68:  Pred:  0 No: 2 done */

    tracer_trace("END: DmecApp::launch\n");
	return;
}

