/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: dmec_app/DmecApp */

#ifndef __c4_DmecApp_H__
#define __c4_DmecApp_H__ 1
#include <keso_types.h>

#define C4_DMECAPP_ID ((class_id_t)4)
#define C4_DMECAPP_OBJ(_obj_) ((c4_DmecApp_t*)(_obj_))

/* class methods prototypes */
/* launch()V */
void c4_DmecApp_m1_launch(object_t* obj0);
/* <init>()V */
void c4_DmecApp_m2__init_(object_t* obj0) __attribute__ ((const)) ;

/* object data */
typedef struct {
/* c4_DmecApp */
/* c3_Task */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
	jbyte _domain_id;
	jbyte _e_domain_id;
	jbyte _task_id;
/* c3_Task */
/* c4_DmecApp */
} c4_DmecApp_t;

#endif

