/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c4_DmecApp.h"


/*
 * call analyse 1 c4_DmecApp_m2__init_
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* dmec_app/DmecApp.<init>()V PURE CONST */

void c4_DmecApp_m2__init_(object_t* obj0) {

	
/*==============================================================/
| 17: public class DmecApp extends Task {
/==============================================================*/
	/* goto c4_DmecApp_m2__init__B6 */;
	
/* c4_DmecApp_m2__init__B6:  Pred:  0 No: 2 done */
	return;
}

