/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c12_String.h"
#include "c6_StringBuffer.h"
#include "char_array.h"


/*
 * call analyse 2 c6_StringBuffer_m4_append
 *
 * c6_StringBuffer_m4_append
 * (valid,"null")
 *
 * c13_DebugOut_m1_println
 * (valid,?null)
 *
 * total (valid,?null)
 */

/* java/lang/StringBuffer.append(Ljava/lang/String;)Ljava/lang/StringBuffer; */

object_t* c6_StringBuffer_m4_append(object_t* obj0,object_t* obj1) {
	jint i7_0;
	jint i4_0;
	jint i6_0;
	jint i11_1;
	jint i13_1;
	jint i4_1;
	object_t* obj9_0;
	object_t* obj5_0;
	object_t* obj24_0;
	object_t* obj16_0;
	object_t* obj3_2;
	jchar c17_1;

	
/*==============================================================/
| 144: 		if (str == null)
/==============================================================*/
	if (obj1!=((object_t*)0)) goto c6_StringBuffer_m4_append_B11;
	
/* c6_StringBuffer_m4_append_B4:  Pred:  0 No: 2 done */
	
/*==============================================================/
| 145: 			return append("null");
/==============================================================*/
	KESO_CHECK_NULLPOINTER(obj0,"append",7);
	obj3_2 = c6_StringBuffer_m4_append((object_t*)obj0,(object_t*)((object_t*) ((object_t**) &str2+1)));
	goto c6_StringBuffer_m4_append_B53;
	
c6_StringBuffer_m4_append_B11: /* Pred:  0 No: 4 done */
	
/*==============================================================/
: 146: 
| 147: 		int n = str.length();
| 148: 		ensureCapacity(length + n);
| 149: 		str.getChars(0, n, data, length);
/==============================================================*/
	KESO_CHECK_NULLPOINTER(obj1,"append",12);
	obj9_0 = (C12_STRING_OBJ(obj1)->c12f1_value);
	KESO_CHECK_NULLPOINTER(obj9_0,"append",12);
	i7_0 = ((array_t*)obj9_0)->size;
	KESO_CHECK_NULLPOINTER(obj0,"append",18);
	i4_0 = ((C6_STRINGBUFFER_OBJ(obj0)->c6f2_length)+i7_0);
	c6_StringBuffer_m2_ensureCapacity((object_t*)obj0,i4_0);
	obj5_0 = (C6_STRINGBUFFER_OBJ(obj0)->c6f1_data);
	i6_0 = (C6_STRINGBUFFER_OBJ(obj0)->c6f2_length);
	if (0x0<0x0) goto cc25559096_c12_String_m2_getChars_B29;
	
/* cc18016247_c12_String_m2_getChars_B4:  Pred:  11 No: 5 done */
	obj24_0 = (C12_STRING_OBJ(obj1)->c12f1_value);
	KESO_CHECK_NULLPOINTER(obj24_0,"append",37);
	if (i7_0>((array_t*)obj24_0)->size) goto cc25559096_c12_String_m2_getChars_B29;
	
/* cc25086455_c12_String_m2_getChars_B13:  Pred:  4 No: 6 done */
	if (i7_0<0x0) goto cc25559096_c12_String_m2_getChars_B29;
	
/* cc22945909_c12_String_m2_getChars_B18:  Pred:  13 No: 7 done */
	KESO_CHECK_NULLPOINTER(obj5_0,"append",37);
	if (((array_t*)obj5_0)->size>=(i7_0+i6_0)) goto cc1744155_c12_String_m2_getChars_B34;
	
cc25559096_c12_String_m2_getChars_B29: /* Pred:  11 4 13 18 No: 8 done */
	while (1) { __asm__ __volatile__ ("nop"); };
	
cc1744155_c12_String_m2_getChars_B34: /* Pred:  18 No: 9 done */
	obj16_0 = (C12_STRING_OBJ(obj1)->c12f1_value);
	i11_1 = 0x0;
	
cc21010507_c12_String_m4_charArrayCopy_B3: /* Pred:  34 10 No: 10 done */
	/* i11_1 = Phi(0,i11_1)  */;
	if (i11_1>=i7_0) goto cc28523022_c12_String_m4_charArrayCopy_B28;
	
/* cc30303902_c12_String_m4_charArrayCopy_B10:  Pred:  3 No: 11 done */
	i13_1 = (i6_0+i11_1);
	KESO_CHECK_ARR_REF(obj16_0,i11_1,"append",37);
	c17_1 = ((char_array_t*)obj16_0)->data[i11_1];
	KESO_CHECK_ARRAY(obj5_0,i13_1,"append",37);
	((char_array_t*)obj5_0)->data[i13_1]=c17_1;
	i11_1 = (i11_1+0x1);
	goto cc21010507_c12_String_m4_charArrayCopy_B3;
	
cc28523022_c12_String_m4_charArrayCopy_B28: /* Pred:  3 No: 12 done */
	
/*==============================================================/
| 150: 		length += n;
: 151: 
| 152: 		return this;
/==============================================================*/
	i4_1 = ((C6_STRINGBUFFER_OBJ(obj0)->c6f2_length)+i7_0);
	(C6_STRINGBUFFER_OBJ(obj0)->c6f2_length) = i4_1;
	obj3_2 = obj0;
	/* goto c6_StringBuffer_m4_append_B53 */;
	
c6_StringBuffer_m4_append_B53: /* Pred:  28 4 No: 3 done */
	/* obj3_2 = Phi(obj0,obj3_2)  */;
	return (object_t*)obj3_2;
}

