/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"


/*
 * call analyse 0 c6_StringBuffer_m7__init_
 */
/* java/lang/StringBuffer.<init>()V */

void c6_StringBuffer_m7__init_(object_t* obj0) {
	jint i1_0;
	object_t* obj2_0;

	
/*==============================================================/
| 35: 		this(minIncrease);
| 36: 	}
/==============================================================*/
	i1_0 = 0x8;
	obj2_0 = keso_alloc_char_array(i1_0);
	KESO_CHECK_NULLPOINTER(obj0,"<init>",3);
	KESO_WRBR((C6_STRINGBUFFER_OBJ(obj0)->c6f1_data),obj2_0);
	(C6_STRINGBUFFER_OBJ(obj0)->c6f2_length) = 0x0;
	/* goto c6_StringBuffer_m7__init__B8 */;
	
/* c6_StringBuffer_m7__init__B8:  Pred:  0 No: 2 done */
	return;
}

