/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"


/*
 * call analyse 0 c6_StringBuffer_m5_setLength
 */
/* java/lang/StringBuffer.setLength(I)V */

void c6_StringBuffer_m5_setLength(object_t* obj0,jint i1) {
	jint i2_1;
	object_t* obj3_1;
	object_t* obj3_2;

	
/*==============================================================/
| 75: 		ensureCapacity(newLength);
| 76: 		if(newLength > length) {
/==============================================================*/
	KESO_CHECK_NULLPOINTER(obj0,"setLength",2);
	c6_StringBuffer_m2_ensureCapacity((object_t*)obj0,i1);
	if (i1<=(C6_STRINGBUFFER_OBJ(obj0)->c6f2_length)) goto c6_StringBuffer_m5_setLength_B39;
	
/* c6_StringBuffer_m5_setLength_B13:  Pred:  0 No: 2 done */
	
/*==============================================================/
| 77: 			 for (int i = length; i < newLength; i++)
/==============================================================*/
	i2_1 = (C6_STRINGBUFFER_OBJ(obj0)->c6f2_length);
	
c6_StringBuffer_m5_setLength_B18: /* Pred:  13 23 No: 3 done */
	/* i2_1 = Phi(i2_1,i2_1)  */;
	if (i2_1>=i1) goto c6_StringBuffer_m5_setLength_B36;
	
/* c6_StringBuffer_m5_setLength_B23:  Pred:  18 No: 4 done */
	
/*==============================================================/
| 78: 				  data[i] = '\u0000';
/==============================================================*/
	obj3_1 = (C6_STRINGBUFFER_OBJ(obj0)->c6f1_data);
	KESO_CHECK_ARR_REF(obj3_1,i2_1,"setLength",29);
	((char_array_t*)obj3_1)->data[i2_1]=0x0;
	i2_1 = (i2_1+0x1);
	goto c6_StringBuffer_m5_setLength_B18;
	
c6_StringBuffer_m5_setLength_B36: /* Pred:  18 No: 5 done */
	goto c6_StringBuffer_m5_setLength_B46;
	
c6_StringBuffer_m5_setLength_B39: /* Pred:  0 No: 8 done */
	
/*==============================================================/
: 79: 		}
: 80: 		else {
| 81: 			 data[newLength] = '\u0000';
/==============================================================*/
	obj3_2 = (C6_STRINGBUFFER_OBJ(obj0)->c6f1_data);
	KESO_CHECK_ARR_REF(obj3_2,i1,"setLength",45);
	((char_array_t*)obj3_2)->data[i1]=0x0;
	
c6_StringBuffer_m5_setLength_B46: /* Pred:  39 36 No: 6 done */
	
/*==============================================================/
: 82: 		}
| 83: 		length = newLength;
| 84: 	}
/==============================================================*/
	(C6_STRINGBUFFER_OBJ(obj0)->c6f2_length) = i1;
	/* goto c6_StringBuffer_m5_setLength_B53 */;
	
/* c6_StringBuffer_m5_setLength_B53:  Pred:  46 No: 7 done */
	return;
}

