/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"


/*
 * call analyse 0 c6_StringBuffer_m1_append
 */
/* java/lang/StringBuffer.append(C)Ljava/lang/StringBuffer; */

object_t* c6_StringBuffer_m1_append(object_t* obj0,jchar c1) {
	jint i3_0;
	jint i3_1;
	jint i3_2;
	object_t* obj4_0;

	
/*==============================================================/
| 120: 		ensureCapacity(length + 1);
| 121: 		data[length] = c;
| 122: 		length++;
| 123: 		return this;
/==============================================================*/
	KESO_CHECK_NULLPOINTER(obj0,"append",2);
	i3_0 = ((C6_STRINGBUFFER_OBJ(obj0)->c6f2_length)+0x1);
	c6_StringBuffer_m2_ensureCapacity((object_t*)obj0,i3_0);
	obj4_0 = (C6_STRINGBUFFER_OBJ(obj0)->c6f1_data);
	i3_1 = (C6_STRINGBUFFER_OBJ(obj0)->c6f2_length);
	KESO_CHECK_ARR_REF(obj4_0,i3_1,"append",19);
	((char_array_t*)obj4_0)->data[i3_1]=c1;
	i3_2 = ((C6_STRINGBUFFER_OBJ(obj0)->c6f2_length)+0x1);
	(C6_STRINGBUFFER_OBJ(obj0)->c6f2_length) = i3_2;
	/* goto c6_StringBuffer_m1_append_B33 */;
	
/* c6_StringBuffer_m1_append_B33:  Pred:  0 No: 2 done */
	return (object_t*)obj0;
}

