/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"


/*
 * call analyse 0 c6_StringBuffer_m6__init_
 */
/* java/lang/StringBuffer.<init>(I)V */

void c6_StringBuffer_m6__init_(object_t* obj0,jint i1) {
	object_t* obj2_0;

	
/*==============================================================/
| 25: 		data = new char[length];
| 26: 		this.length = 0;
| 27: 	}
/==============================================================*/
	obj2_0 = keso_alloc_char_array(i1);
	KESO_CHECK_NULLPOINTER(obj0,"<init>",8);
	KESO_WRBR((C6_STRINGBUFFER_OBJ(obj0)->c6f1_data),obj2_0);
	(C6_STRINGBUFFER_OBJ(obj0)->c6f2_length) = 0x0;
	/* goto c6_StringBuffer_m6__init__B18 */;
	
/* c6_StringBuffer_m6__init__B18:  Pred:  0 No: 2 done */
	return;
}

