/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c7_NativeTestSupport.h"
#include "c1_Object.h"


/*
 * call analyse 0 c7_NativeTestSupport_m3__init_
 */
/* dmec/NativeTestSupport.<init>()V */

void c7_NativeTestSupport_m3__init_(object_t* obj0) {

	
/*==============================================================/
| 6: null
/==============================================================*/
	KESO_CHECK_NULLPOINTER(obj0,"<init>",1);
	c1_Object_m1__init_((object_t*)obj0);
	/* goto c7_NativeTestSupport_m3__init__B6 */;
	
/* c7_NativeTestSupport_m3__init__B6:  Pred:  0 No: 0 done */
	return;
}

