/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c7_NativeTestSupport.h"
#include "c30_Picture.h"


/*
 * call analyse 2 c7_NativeTestSupport_m1_createPicture
 *
 * c4_DmecApp_m1_launch
 * (176,144,0)
 *
 * c4_DmecApp_m1_launch
 * (176,144,1)
 *
 * total (176,144,[0,1])
 */

/* dmec/NativeTestSupport.createPicture(III)Ldmec/Picture; */

object_t* c7_NativeTestSupport_m1_createPicture(jint i0,jint i1,jint i2) {
	c30_Picture_t* pic = KESO_ALLOC(C30_PICTURE_ID,sizeof(c30_Picture_t),0);
	((c30_Picture_t*) pic)->__inner = testSupport_createPicture((unsigned int) i0, (unsigned int) i1, (unsigned int) i2);
	return pic;
}

