/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c7_NativeTestSupport.h"
#include "c30_Picture.h"
#include "c31_PictureMotionCounterpart.h"

/*
 * call analyse 1 c7_NativeTestSupport_m2_testPictureMotionCounterpart
 *
 * c4_DmecApp_m1_launch
 * (?null,176,144,?null,?null)
 *
 * total (?null,176,144,?null,?null)
 */

/* dmec/NativeTestSupport.testPictureMotionCounterpart(Ldmec/PictureMotionCounterpart;IILdmec/Picture;Ldmec/Picture;)V */

void c7_NativeTestSupport_m2_testPictureMotionCounterpart(object_t* obj0,jint i1,jint i2,object_t* obj3,object_t* obj4) {
    testSupport_testPictureMotionCounterpart(
        ((c31_PictureMotionCounterpart_t*) obj0)->__inner,
        (unsigned int) i1,
        (unsigned int) i2,
        ((c30_Picture_t*) obj3)->__inner,
        ((c30_Picture_t*) obj4)->__inner);
}

