/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c8_Math.h"


/*
 * call analyse 0 c8_Math_m3__init_
 */
/* java/lang/Math.<init>()V PURE CONST */

void c8_Math_m3__init_(object_t* obj0) {

	
/*==============================================================/
| 17: public final class Math 
/==============================================================*/
	/* goto c8_Math_m3__init__B6 */;
	
/* c8_Math_m3__init__B6:  Pred:  0 No: 2 done */
	return;
}

