/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: java/lang/Throwable */

#ifndef __c9_Throwable_H__
#define __c9_Throwable_H__ 1
#include <keso_types.h>

#define C9_THROWABLE_ID ((class_id_t)9)
#define C9_THROWABLE_OBJ(_obj_) ((c9_Throwable_t*)((object_t**)(_obj_)-1))

/* class methods prototypes */
/* <init>()V */
void c9_Throwable_m1__init_(object_t* obj0);

/* object data */
typedef struct {
/* c9_Throwable */
	object_t* c9f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c9_Throwable */
} c9_Throwable_t;

#endif

