/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c9_Throwable.h"


/*
 * call analyse 0 c9_Throwable_m1__init_
 */
/* java/lang/Throwable.<init>()V */

void c9_Throwable_m1__init_(object_t* obj0) {

	
/*==============================================================/
| 23: 	}	
/==============================================================*/
	/* goto c9_Throwable_m1__init__B11 */;
	
/* c9_Throwable_m1__init__B11:  Pred:  0 No: 2 done */
	return;
}

