/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"


#include "char_array.h"

object_t	*keso_alloc_char_array(array_size_t size) {
	array_t* array;
	array=(array_t*)KESO_ALLOC(CHAR_ARRAY_ID,sizeof(array_t)+(size*sizeof(jchar)),0);
	array->size=size;
	return (object_t*)array;
}

