/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: [C */

#ifndef __char_array_H__
#define __char_array_H__ 1
#include <keso_types.h>
#include <keso_types.h>

#define CHAR_ARRAY_ID ((class_id_t)2)
typedef struct {
ARRAY_HEADER
	jchar data[1];
} char_array_t;

object_t	*keso_alloc_char_array(array_size_t size);

#endif

