/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define TARGET_LINUX_JOSEK

#include <keso_types.h>

typedef unsigned short class_id_t;
typedef unsigned long  array_size_t;

#define OBJECT_HEADER \
	unsigned char gcinfo;\
	unsigned char bitfld1;\
	class_id_t class_id;\

typedef struct {
OBJECT_HEADER
} object_t;

typedef struct {
	class_id_t     type_range;
	unsigned short size;
	unsigned char ifaces;
	unsigned char roff;
} class_t;
#define ARRAY_HEADER \
OBJECT_HEADER\
	array_size_t size;
#include "c1_Object.h"
#include "char_array.h"
#include "c3_Task.h"
#include "c4_DmecApp.h"
#include "c5_PictureMotionEstimator.h"
#include "c6_StringBuffer.h"
#include "c7_NativeTestSupport.h"
#include "c8_Math.h"
#include "c9_Throwable.h"
#include "c10_RuntimeException.h"
#include "c11_StringIndexOutOfBoundsException.h"
#include "c12_String.h"
#include "c13_DebugOut.h"

class_t class_store[] = {
 /* 0 RESERVED */
 /* 1	java/lang/Object */
 {.type_range=14, .size=sizeof(c1_Object_t), .ifaces=0, .roff=0},
 /* 2	[C */
 {.type_range=2, .size=sizeof(jchar), .ifaces=0, .roff=0},
 /* 3	keso/core/Task */
 {.type_range=4, .size=sizeof(c3_Task_t), .ifaces=1, .roff=0},
 /* 4	dmec_app/DmecApp */
 {.type_range=4, .size=sizeof(c4_DmecApp_t), .ifaces=1, .roff=0},
 /* 5	dmec/PictureMotionEstimator */
 {.type_range=5, .size=sizeof(c5_PictureMotionEstimator_t), .ifaces=0, .roff=0},
 /* 6	java/lang/StringBuffer */
 {.type_range=6, .size=sizeof(c6_StringBuffer_t), .ifaces=0, .roff=1},
 /* 7	dmec/NativeTestSupport */
 {.type_range=7, .size=sizeof(c7_NativeTestSupport_t), .ifaces=0, .roff=0},
 /* 8	java/lang/Math */
 {.type_range=8, .size=sizeof(c8_Math_t), .ifaces=0, .roff=0},
 /* 9	java/lang/Throwable */
 {.type_range=11, .size=sizeof(c9_Throwable_t), .ifaces=0, .roff=1},
 /* 10	java/lang/RuntimeException */
 {.type_range=11, .size=sizeof(c10_RuntimeException_t), .ifaces=0, .roff=1},
 /* 11	java/lang/StringIndexOutOfBoundsException */
 {.type_range=11, .size=sizeof(c11_StringIndexOutOfBoundsException_t), .ifaces=0, .roff=1},
 /* 12	java/lang/String */
 {.type_range=12, .size=sizeof(c12_String_t), .ifaces=0, .roff=1},
 /* 13	test/DebugOut */
 {.type_range=13, .size=sizeof(c13_DebugOut_t), .ifaces=0, .roff=0},
};
#define CLASSSTORE_SIZE 13
#define CLASS(_id_) class_store[((_id_)-1)]
#define CLS_ROFF(_cls_) CLASS(_cls_).roff

char *class_names[] = {
	"java/lang/Object",
	"[C",
	"keso/core/Task",
	"dmec_app/DmecApp",
	"dmec/PictureMotionEstimator",
	"java/lang/StringBuffer",
	"dmec/NativeTestSupport",
	"java/lang/Math",
	"java/lang/Throwable",
	"java/lang/RuntimeException",
	"java/lang/StringIndexOutOfBoundsException",
	"java/lang/String",
	"test/DebugOut",
};

void dump_class_store() {
	int i;
	printf("cls:type    :size:ifs:roff:classname\n");
	for (i=0;i<CLASSSTORE_SIZE;i++) {
		int cid = i+1;
		class_t cls = CLASS(cid);
		printf("%3d:%3d -%3d:%4d:%3d:%4d:",cid,cid,cls.type_range,cls.size,cls.ifaces,CLS_ROFF(cid));
		printf("%s\n",class_names[i]);
	}
}


void dump_gc_stat() {
	FILE *log;
	if (NULL==(log=fopen("gc.log","r"))) { perror("gc.log"); exit(1); }
	printf("E: time :total:free:slots:\n");
	while (!feof(log)) {
		char event;
		unsigned int time, total, free, size, did, tid, pos, cid;
		fscanf(log,"%c:%u:%u:%u:%u:%u:%u:%u:%u\n",&event,&time,&total,&free,&size,&did,&tid,&pos,&cid);
		printf("%c:%6u:%5u:%4u:%5u:",event,time,total,free,size);
		switch (event) {
		case 'a':
			printf("task %u alloc(%s)\n",tid,class_names[cid-1]);
			break;
		default:
			printf("domain %u\n",did);
		}
	}
	fclose(log);
}


int main(int argc, char* argv[]) {
	if (argc<2) { printf("usage: %s [cls|gc]\n",argv[0]); exit(1); }
	if (strncmp(argv[1], "cls", 3)==0) {
		dump_class_store(); exit(0);
	} else if (strncmp(argv[1], "gc", 2)==0) {
		dump_gc_stat();exit(0);
	}
	return 1;
}
