/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"
#include "c13_DebugOut.h"


/*
 * call analyse 2 c13_DebugOut_m4_raw_print
 *
 * c13_DebugOut_m1_println
 * (?null)
 *
 * c13_DebugOut_m2_println
 * (?null)
 *
 * total (?null)
 */

/* test/DebugOut.raw_print(Ljava/lang/StringBuffer;)V */
#include <keso_support.h>

void c13_DebugOut_m4_raw_print(object_t* obj0) {
	KESO_CHECK_NULLPOINTER(obj0,"c13_DebugOut_m4_raw_print",-1);
	char_array_t* char_array = (char_array_t*)(C6_STRINGBUFFER_OBJ(obj0)->c6f1_data);
	write(1, char_array->data, (C6_STRINGBUFFER_OBJ(obj0)->c6f2_length));
	return;
}

