/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: java/lang/StringIndexOutOfBoundsException */

#ifndef __c11_StringIndexOutOfBoundsException_H__
#define __c11_StringIndexOutOfBoundsException_H__ 1
#include <keso_types.h>

#define C11_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID ((class_id_t)11)
#define C11_STRINGINDEXOUTOFBOUNDSEXCEPTION_OBJ(_obj_) ((c11_StringIndexOutOfBoundsException_t*)((object_t**)(_obj_)-1))

/* class methods prototypes */
/* <init>()V */
void c11_StringIndexOutOfBoundsException_m1__init_(object_t* obj0) __attribute__ ((const)) ;

/* object data */
typedef struct {
/* c11_StringIndexOutOfBoundsException */
/* c10_RuntimeException */
/* c9_Throwable */
	object_t* c9f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c9_Throwable */
/* c10_RuntimeException */
/* c11_StringIndexOutOfBoundsException */
} c11_StringIndexOutOfBoundsException_t;

#endif

