/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: dmec/NativeTestSupport */

#ifndef __c7_NativeTestSupport_H__
#define __c7_NativeTestSupport_H__ 1
#include <keso_types.h>

#define C7_NATIVETESTSUPPORT_ID ((class_id_t)7)
#define C7_NATIVETESTSUPPORT_OBJ(_obj_) ((c7_NativeTestSupport_t*)(_obj_))

/* class methods prototypes */
/* testPictureMotionCounterpart(Ldmec/PictureMotionCounterpart;IILdmec/Picture;Ldmec/Picture;)V */
void c7_NativeTestSupport_m2_testPictureMotionCounterpart(object_t* obj0,jint i1,jint i2,object_t* obj3,object_t* obj4);
#include <app_include/c_test_support.h>
/* createPicture(III)Ldmec/Picture; */
object_t* c7_NativeTestSupport_m1_createPicture(jint i0,jint i1,jint i2);
/* <init>()V */
void c7_NativeTestSupport_m3__init_(object_t* obj0);

/* object data */
typedef struct {
/* c7_NativeTestSupport */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c7_NativeTestSupport */
} c7_NativeTestSupport_t;

#endif

