/* Generated By:JavaCC: Do not edit this line. KesoDataManagerReaderConstants.java */
package keso.editor.data.datamanager.reader;

public interface KesoDataManagerReaderConstants {

  int EOF = 0;
  int LINECOMMENT = 5;
  int CANHAVE = 6;
  int OR = 7;
  int AND = 8;
  int WITHRESTRICTION = 9;
  int IDENTIFIER = 10;
  int NUMBER = 11;
  int LETTER = 12;
  int DIGIT = 13;
  int LPAREN = 14;
  int RPAREN = 15;
  int LBRACE = 16;
  int RBRACE = 17;
  int DQUOTE = 18;
  int LBRACKET = 19;
  int RBRACKET = 20;
  int SEMICOLON = 21;
  int COMMA = 22;
  int ASSIGNMENT = 23;
  int DOT = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINECOMMENT>",
    "\"CAN HAVE\"",
    "\"OR\"",
    "\"AND\"",
    "\"WITH RESTRICTION\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\".\"",
  };

}
