/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c13_DebugOut.h"


/*
 * call analyse 0 c13_DebugOut_m5__init_
 */
/* test/DebugOut.<init>()V PURE CONST */

void c13_DebugOut_m5__init_(object_t* obj0) {

	
/*==============================================================/
| 6: final public class DebugOut {
/==============================================================*/
	/* goto c13_DebugOut_m5__init__B6 */;
	
/* c13_DebugOut_m5__init__B6:  Pred:  0 No: 2 done */
	return;
}

