/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: java/lang/StringBuffer */

#ifndef __c6_StringBuffer_H__
#define __c6_StringBuffer_H__ 1
#include <keso_types.h>

#define C6_STRINGBUFFER_ID ((class_id_t)6)
#define C6_STRINGBUFFER_OBJ(_obj_) ((c6_StringBuffer_t*)((object_t**)(_obj_)-1))

/* class methods prototypes */
/* append(C)Ljava/lang/StringBuffer; */
object_t* c6_StringBuffer_m1_append(object_t* obj0,jchar c1);
/* copy_chars([CI[CII)V */
void c6_StringBuffer_m3_copy_chars(object_t* obj0,jint i1,object_t* obj2,jint i3,jint i4);
/* append(Ljava/lang/String;)Ljava/lang/StringBuffer; */
object_t* c6_StringBuffer_m4_append(object_t* obj0,object_t* obj1);
/* ensureCapacity(I)V */
void c6_StringBuffer_m2_ensureCapacity(object_t* obj0,jint i1);
/* setLength(I)V */
void c6_StringBuffer_m5_setLength(object_t* obj0,jint i1);
/* <init>(I)V */
void c6_StringBuffer_m6__init_(object_t* obj0,jint i1);
/* <init>()V */
void c6_StringBuffer_m7__init_(object_t* obj0);

/* object data */
typedef struct {
/* c6_StringBuffer */
	object_t* c6f1_data;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
	jint c6f2_length;
/* c6_StringBuffer */
} c6_StringBuffer_t;

#endif

