/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c11_StringIndexOutOfBoundsException.h"
#include "c12_String.h"


/*
 * call analyse 2 c12_String_m3_out_of_bounds
 *
 * c6_StringBuffer_m4_append
 * (valid)
 *
 * c12_String_m2_getChars
 * (valid)
 *
 * total (valid)
 */

/* java/lang/String.out_of_bounds()Ljava/lang/StringIndexOutOfBoundsException; */

object_t* c12_String_m3_out_of_bounds(object_t* obj0) {
	object_t* obj2_0;

	
/*==============================================================/
| 496: 		return new StringIndexOutOfBoundsException();
/==============================================================*/
	obj2_0 = KESO_ALLOC(C11_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID,sizeof(c11_StringIndexOutOfBoundsException_t),1);
	/* goto c12_String_m3_out_of_bounds_B9 */;
	
/* c12_String_m3_out_of_bounds_B9:  Pred:  0 No: 2 done */
	return (object_t*)obj2_0;
}

