/* Generated By:JavaCC: Do not edit this line. KesoFilterReaderConstants.java */
package keso.editor.filter.manager.reader;

public interface KesoFilterReaderConstants {

  int EOF = 0;
  int LINECOMMENT = 5;
  int FILTER = 6;
  int COMBINEDFILTER = 7;
  int WITHOUT_CLASS_TYPE = 8;
  int TWO_STAGE_OPERATION = 9;
  int GET_PARENT_OF_TYPE = 10;
  int FILTER_BY_CLASSTYPE = 11;
  int IDENTIFIER = 12;
  int NUMBER = 13;
  int LETTER = 14;
  int DIGIT = 15;
  int LBRACE = 16;
  int RBRACE = 17;
  int DQUOTE = 18;
  int LBRACKET = 19;
  int RBRACKET = 20;
  int SEMICOLON = 21;
  int COMMA = 22;
  int ASSIGNMENT = 23;
  int DOT = 24;
  int LPAREN = 25;
  int RPAREN = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LINECOMMENT>",
    "\"Filter\"",
    "\"CombinedFilter\"",
    "<WITHOUT_CLASS_TYPE>",
    "<TWO_STAGE_OPERATION>",
    "\"GET_PARENT_OF_CLASSTYPE\"",
    "\"FILTER_BY_CLASSTYPE\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\".\"",
    "\"(\"",
    "\")\"",
  };

}
