/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c12_String.h"
#include "char_array.h"


/*
 * call analyse 0 c12_String_m4_charArrayCopy
 */
/* java/lang/String.charArrayCopy([CI[CII)V */

void c12_String_m4_charArrayCopy(object_t* obj0,jint i1,object_t* obj2,jint i3,jint i4) {
	jint i5_1;
	jint i6_1;
	jint i7_1;
	jchar c8_1;

	i5_1 = 0x0;
	
c12_String_m4_charArrayCopy_B3: /* Pred:  0 10 No: 2 done */
	
/*==============================================================/
| 490: 		for(int i=0; i<count; i++) {
/==============================================================*/
	/* i5_1 = Phi(0,i5_1)  */;
	if (i5_1>=i4) goto c12_String_m4_charArrayCopy_B28;
	
/* c12_String_m4_charArrayCopy_B10:  Pred:  3 No: 3 done */
	
/*==============================================================/
| 491: 			dst[dstOffset+i] = src[srcOffset+i];
/==============================================================*/
	i6_1 = (i3+i5_1);
	i7_1 = (i1+i5_1);
	KESO_CHECK_ARR_REF(obj0,i7_1,"charArrayCopy",20);
	c8_1 = ((char_array_t*)obj0)->data[i7_1];
	KESO_CHECK_ARR_REF(obj2,i6_1,"charArrayCopy",21);
	((char_array_t*)obj2)->data[i6_1]=c8_1;
	i5_1 = (i5_1+0x1);
	goto c12_String_m4_charArrayCopy_B3;
	
c12_String_m4_charArrayCopy_B28: /* Pred:  3 No: 4 done */
	
/*==============================================================/
: 492: 		}
| 493: 	}
/==============================================================*/
	/* goto c12_String_m4_charArrayCopy_B30 */;
	
/* c12_String_m4_charArrayCopy_B30:  Pred:  28 No: 5 done */
	return;
}

