   int main() {
      //...
      component->method();
   }
   //Assembly generated code
   82c9 <main>:
   //...
   8339: call a200 <OS_Box>
   //...
   a200 <OS_Box>
   //...
   //call the method through Dispatcher
   a237: call *%esi
   // ...
   aae0 <Agent<Component>::method>
   //...
   //call Adapter<Component>::method
   ab0a: jmp *%ecx
   //...
   a500 <Adapter<Component>::method>
   //...
   //call the component method
   a512: jmp *%ecx