<family name="Address_Space" type="abstraction"
  class="uniform">
  ...
 <member name="Flat_AS" type="exclusive"
   performance="1" codesize="1" energy="1">
  ...
 <member/>
  ...
 <member name="Paged_AS" type="exclusive"
   performance="3" codesize="5" energy="7">
   ...
 <member/>
  ...
</family>
