/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: dmec/PictureMotionCounterpart */

#ifndef __c31_PictureMotionCounterpart_H__
#define __c31_PictureMotionCounterpart_H__ 1
#include <keso_types.h>

#define C31_PICTUREMOTIONCOUNTERPART_ID ((class_id_t)31)
#define C31_PICTUREMOTIONCOUNTERPART_OBJ(_obj_) ((c31_PictureMotionCounterpart_t*)(_obj_))

/* class methods prototypes */
/* <init>()V */
void c31_PictureMotionCounterpart_m1__init_(object_t* obj0);

/* object data */
typedef struct {
#include <app_include/c_picture.h>
/* c31_PictureMotionCounterpart */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
	void* __inner;
/* c31_PictureMotionCounterpart */
} c31_PictureMotionCounterpart_t;

#endif

