/* Stuff to suport a specific application - "autogenerated" by the OIL compiler ;) */
#include <epos2osek/configurations.hh>
#include <epos2osek_defs.h>

/* Application source: single_task_test.cc */

// Application tasks
int func_aTask(void);
/* BasicTask constructor parameters:
 *  @entry : function pointer
 *  @taskIdentity : TaskType
 *  @taskState : TaskStateType
 *  @taskPriority : SomeTaskPriorities
 */
BasicTask * appTasks[1];

BasicTask ** CreateAllTasks(int & numberOfTasks) {
    appTasks[0] = new BasicTask(func_aTask, 0, OSEK_READY, OSEK_NORMAL);
    numberOfTasks = 1;
    return appTasks;
}

/* ------------------------------------------------------------------------- */

/* Application ------------------------------------------------------------- */

#include <epos2osek.h>

int main() {
    print("At main function\n");
    StartOS(OSDEFAULTAPPMODE);
    return 0;
}

void StartupHook() {
    print("At StartupHook\n");
}

TASK(aTask) {
    print("I am a task!\n");
	
	TerminateTask();
}

/* ------------------------------------------------------------------------- */
