function plot_latency(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 11-Feb-2010 16:17:21

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'XTickLabel',{'No CSMA-CA/ACK','No ACK','No CSMA-CA','Full','Full/Beacon-enabled'},...
    'XTick',[1 2 3 4 5],...
    'FontSize',11);
box('on');
hold('all');

% Create ylabel
ylabel('Latency (ms)','FontWeight','demi','FontSize',12);

% Create bar
bar(yvector1,'FaceColor',[0 0 1],'BarWidth',0.6,'BaseValue',1,...
    'DisplayName','Latency');

