/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: test/DebugOut */

#ifndef __c13_DebugOut_H__
#define __c13_DebugOut_H__ 1
#include <keso_types.h>

#define C13_DEBUGOUT_ID ((class_id_t)13)
#define C13_DEBUGOUT_OBJ(_obj_) ((c13_DebugOut_t*)(_obj_))

/* class methods prototypes */
/* println(Ljava/lang/String;)V */
void c13_DebugOut_m1_println(object_t* obj0);
/* <clinit>()V */
void c13_DebugOut_m3__clinit_(void);
/* println()V */
void c13_DebugOut_m2_println(void) __attribute__ ((pure)) ;
/* raw_print(Ljava/lang/StringBuffer;)V */
void c13_DebugOut_m4_raw_print(object_t* obj0);
/* <init>()V */
void c13_DebugOut_m5__init_(object_t* obj0) __attribute__ ((const)) ;

/* object data */
typedef struct {
/* c13_DebugOut */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c13_DebugOut */
} c13_DebugOut_t;

#endif

