<family name="Network" type="abstraction"
  class="uniform">
  ...
 <member name="Single_Hop" type="inclusive"
   performance="3" codesize="2" energy="8">
  ...
 <member/>
  ...
 <member name="Multi_Hop" type="inclusive"
   performance="7" codesize="5" energy="3">
   ...
 <member/>
  ...
</family>
