/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c8_Math.h"


/*
 * call analyse 0 c8_Math_m1_min
 */
/* java/lang/Math.min(II)I PURE CONST */

jint c8_Math_m1_min(jint i0,jint i1) {
	jint i3_2;

	
/*==============================================================/
| 94: 	return (a < b ? a : b);
/==============================================================*/
	if (i0>=i1) goto c8_Math_m1_min_B9;
	
/* c8_Math_m1_min_B5:  Pred:  0 No: 2 done */
	i3_2 = i0;
	goto c8_Math_m1_min_B10;
	
c8_Math_m1_min_B9: /* Pred:  0 No: 5 done */
	i3_2 = i1;
	
c8_Math_m1_min_B10: /* Pred:  9 5 No: 3 done */
	/* i3_2 = Phi(i1,i0)  */;
	/* goto c8_Math_m1_min_B12 */;
	
/* c8_Math_m1_min_B12:  Pred:  10 No: 4 done */
	return i3_2;
}

