/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c5_PictureMotionEstimator.h"
#include "c30_Picture.h"
#include "c31_PictureMotionCounterpart.h"

#include <utility/tracer_c.h>

/*
 * call analyse 1 c5_PictureMotionEstimator_m1_match
 *
 * c4_DmecApp_m1_launch
 * (valid,?null,?null)
 *
 * total (valid,?null,?null)
 */

/* dmec/PictureMotionEstimator.match(Ldmec/Picture;Ldmec/Picture;)Ldmec/PictureMotionCounterpart; */

object_t* c5_PictureMotionEstimator_m1_match(object_t* obj0,object_t* obj1,object_t* obj2) {
    /* tracer_trace("C5 match\n"); */
    
    ((c31_PictureMotionCounterpart_t*) ((c5_PictureMotionEstimator_t*) obj0)->__pmcWrapper)->__inner = 
        pme_match(
            ((c5_PictureMotionEstimator_t*)obj0)->__inner, 
            ((c30_Picture_t*) obj1)->__inner, 
            ((c30_Picture_t*) obj2)->__inner); /* Since there is no cXX_PictureMotionCounterpart_t */

    /* tracer_trace("C5 match end\n"); */

	return ((c5_PictureMotionEstimator_t*)obj0)->__pmcWrapper;
}

