/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: java/lang/Object */

#ifndef __c1_Object_H__
#define __c1_Object_H__ 1
#include <keso_types.h>

#define C1_OBJECT_ID ((class_id_t)1)
#define C1_OBJECT_OBJ(_obj_) ((c1_Object_t*)(_obj_))

/* class methods prototypes */
/* <init>()V */
void c1_Object_m1__init_(object_t* obj0);

/* object data */
typedef struct {
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
} c1_Object_t;

#endif

