/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c11_StringIndexOutOfBoundsException.h"


/*
 * call analyse 0 c11_StringIndexOutOfBoundsException_m1__init_
 */
/* java/lang/StringIndexOutOfBoundsException.<init>()V PURE CONST */

void c11_StringIndexOutOfBoundsException_m1__init_(object_t* obj0) {

	
/*==============================================================/
| 19:     public StringIndexOutOfBoundsException() { super(); }
/==============================================================*/
	/* goto c11_StringIndexOutOfBoundsException_m1__init__B6 */;
	
/* c11_StringIndexOutOfBoundsException_m1__init__B6:  Pred:  0 No: 2 done */
	return;
}

