/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c3_Task.h"


/*
 * call analyse 1 c3_Task_m1__init_
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* keso/core/Task.<init>()V */

void c3_Task_m1__init_(object_t* obj0) {

	
/*==============================================================/
| 34: 	protected Task() {  }
/==============================================================*/
	/* goto c3_Task_m1__init__B6 */;
	
/* c3_Task_m1__init__B6:  Pred:  0 No: 2 done */
	return;
}

