/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

/* Class: java/lang/Math */

#ifndef __c8_Math_H__
#define __c8_Math_H__ 1
#include <keso_types.h>

#define C8_MATH_ID ((class_id_t)8)
#define C8_MATH_OBJ(_obj_) ((c8_Math_t*)(_obj_))

/* class methods prototypes */
/* min(II)I */
jint c8_Math_m1_min(jint i0,jint i1) __attribute__ ((const)) ;
/* max(II)I */
jint c8_Math_m2_max(jint i0,jint i1) __attribute__ ((const)) ;
/* <init>()V */
void c8_Math_m3__init_(object_t* obj0) __attribute__ ((const)) ;

/* object data */
typedef struct {
/* c8_Math */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c8_Math */
} c8_Math_t;

#endif

