function plot_sw_hw(sw_hw_swsink_hwsink1)
%CREATEFIGURE(SW_HW_SWSINK_HWSINK1)
%  SW_HW_SWSINK_HWSINK1:  bar yvector

%  Auto-generated by MATLAB on 11-Jun-2010 17:19:52

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes('Parent',figure1,'XTickLabel',{'SW','HW','SW/HW (a)','SW/HW (b)'},...
    'XTick',[1 2 3 4],'FontSize',12);
box('on');
hold('all');

% Create bar
bar(sw_hw_swsink_hwsink1,'DisplayName','sw_hw_swsink_hwsink');

% Create xlabel
xlabel('Serial data flow implementations','FontSize',12);

% Create ylabel
ylabel('Latency (microseconds)','FontSize',12);

