#!/bin/csh
acsun < InterSymp.txt >InterSymp.tex

platex InterSymp.tex
rm -f InterSymp.tex
#dvips -D 1270 -c 1 -t a4 -F -U -o se.ps se.dvi
if ($1) then
  if ($2) then
    dvips -D 1270 -c 1 -t a4 -F -U -p $1 -n $2 -o InterSymp.ps InterSymp.dvi
  else
    dvips -D 1270 -c 1 -t a4 -F -U -p $1 -o InterSymp.ps InterSymp.dvi
  endif
else
  dvips -D 1270 -c 1 -t a4 -F -U -o InterSymp.ps InterSymp.dvi
endif

