/* Generated By:JavaCC: Do not edit this line. KesoPropertyManagerReaderConstants.java */
package keso.editor.property.propertymanager.reader;

public interface KesoPropertyManagerReaderConstants {

  int EOF = 0;
  int DESCRIPTION = 5;
  int LINECOMMENT = 6;
  int DEFAULTPROPERTY = 7;
  int NOTNULL = 8;
  int MUSTEXIST = 9;
  int LOCALYUNIQUE = 10;
  int GLOBALYUNIQUE = 11;
  int VALUE = 12;
  int INTEGER = 13;
  int STRING = 14;
  int COMPLEXBOOLEAN = 15;
  int COMPLEXUNQUOTEDSTRING = 16;
  int INTEGERARRAY = 17;
  int IDENTIFIER = 18;
  int NUMBER = 19;
  int LETTER = 20;
  int DIGIT = 21;
  int LBRACE = 22;
  int RBRACE = 23;
  int DQUOTE = 24;
  int LBRACKET = 25;
  int RBRACKET = 26;
  int SEMICOLON = 27;
  int COMMA = 28;
  int ASSIGNMENT = 29;
  int DOT = 30;
  int LPAREN = 31;
  int RPAREN = 32;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<DESCRIPTION>",
    "<LINECOMMENT>",
    "\"default\"",
    "\"NOT NULL\"",
    "\"MUST EXIST\"",
    "\"LOCALY UNIQUE\"",
    "\"GLOBALY UNIQUE\"",
    "\"value\"",
    "\"Integer\"",
    "\"String\"",
    "\"ComplexBoolean\"",
    "\"ComplexUnquotedString\"",
    "\"IntegerArray\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\".\"",
    "\"(\"",
    "\")\"",
  };

}
