/* Generated By:JavaCC: Do not edit this line. KesoPropertyManagerReaderTokenManager.java */
package keso.editor.property.propertymanager.reader;
import java.io.*;
import java.util.Vector;
import keso.editor.property.*;
import keso.editor.property.propertymanager.*;

/**
 * @author  Wilhelm Haas
 */
public class KesoPropertyManagerReaderTokenManager implements KesoPropertyManagerReaderConstants
{
  public  java.io.PrintStream debugStream = System.out;
  /**
 * @param debugStream  the debugStream to set
 * @uml.property  name="debugStream"
 */
public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x3ff80L) != 0L)
         {
            jjmatchedKind = 18;
            return 5;
         }
         return -1;
      case 1:
         if ((active0 & 0x3ff80L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 1;
            return 5;
         }
         return -1;
      case 2:
         if ((active0 & 0x3ff80L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 2;
            return 5;
         }
         return -1;
      case 3:
         if ((active0 & 0x100L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x3fe80L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 3;
            return 5;
         }
         return -1;
      case 4:
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x100L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x3ec80L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 4;
            return 5;
         }
         if ((active0 & 0x1000L) != 0L)
            return 5;
         return -1;
      case 5:
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x100L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x4000L) != 0L)
            return 5;
         if ((active0 & 0x3ac80L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 5;
            return 5;
         }
         return -1;
      case 6:
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x100L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x18800L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return 5;
         }
         if ((active0 & 0x22080L) != 0L)
            return 5;
         return -1;
      case 7:
         if ((active0 & 0x800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x100L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x38000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 7;
            return 5;
         }
         return -1;
      case 8:
         if ((active0 & 0x800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x38000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 8;
            return 5;
         }
         return -1;
      case 9:
         if ((active0 & 0x800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x200L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x38000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 9;
            return 5;
         }
         return -1;
      case 10:
         if ((active0 & 0x800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x38000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 10;
            return 5;
         }
         return -1;
      case 11:
         if ((active0 & 0x800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x18000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 11;
            return 5;
         }
         if ((active0 & 0x20000L) != 0L)
            return 5;
         return -1;
      case 12:
         if ((active0 & 0x800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x18000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 12;
            return 5;
         }
         return -1;
      case 13:
         if ((active0 & 0x800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 18;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 13;
            return 5;
         }
         if ((active0 & 0x8000L) != 0L)
            return 5;
         return -1;
      case 14:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 14;
            return 5;
         }
         return -1;
      case 15:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 15;
            return 5;
         }
         return -1;
      case 16:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 16;
            return 5;
         }
         return -1;
      case 17:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 17;
            return 5;
         }
         return -1;
      case 18:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 18;
            return 5;
         }
         return -1;
      case 19:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 19;
            return 5;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStopAtPos(0, 24);
      case 40:
         return jjStopAtPos(0, 31);
      case 41:
         return jjStopAtPos(0, 32);
      case 44:
         return jjStopAtPos(0, 28);
      case 46:
         return jjStopAtPos(0, 30);
      case 59:
         return jjStopAtPos(0, 27);
      case 61:
         return jjStopAtPos(0, 29);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x18000L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x22000L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 91:
         return jjStopAtPos(0, 25);
      case 93:
         return jjStopAtPos(0, 26);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 123:
         return jjStopAtPos(0, 22);
      case 125:
         return jjStopAtPos(0, 23);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x800L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x500L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x200L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x22000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x18000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x18000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x22000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 66:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x22000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x18000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x100L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 5);
         break;
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x22000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x18000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0x200L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 85:
         return jjMoveStringLiteralDfa6_0(active0, 0x100L);
      case 89:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x3a000L);
      case 103:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 5);
         break;
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa7_0(active0, 0x400L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x100L);
      case 88:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 89:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 114:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      case 116:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 7, 5);
         break;
      case 120:
         return jjMoveStringLiteralDfa7_0(active0, 0x18000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0x800L);
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
      case 66:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x200L);
      case 76:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(7, 8);
         break;
      case 85:
         return jjMoveStringLiteralDfa8_0(active0, 0x10400L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 85:
         return jjMoveStringLiteralDfa9_0(active0, 0x800L);
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa10_0(active0, 0x400L);
      case 78:
         return jjMoveStringLiteralDfa10_0(active0, 0x800L);
      case 84:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(9, 9);
         break;
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000L);
      case 113:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000L);
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private final int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa11_0(active0, 0x800L);
      case 81:
         return jjMoveStringLiteralDfa11_0(active0, 0x400L);
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000L);
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000L);
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private final int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 81:
         return jjMoveStringLiteralDfa12_0(active0, 0x800L);
      case 85:
         return jjMoveStringLiteralDfa12_0(active0, 0x400L);
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x8000L);
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000L);
      case 121:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(11, 17, 5);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private final int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(12, 10);
         break;
      case 85:
         return jjMoveStringLiteralDfa13_0(active0, 0x800L);
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0x8000L);
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private final int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(13, 11);
         break;
      case 101:
         return jjMoveStringLiteralDfa14_0(active0, 0x10000L);
      case 110:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(13, 15, 5);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private final int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa15_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private final int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 83:
         return jjMoveStringLiteralDfa16_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private final int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 116:
         return jjMoveStringLiteralDfa17_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private final int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 114:
         return jjMoveStringLiteralDfa18_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
private final int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa19_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
private final int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa20_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
private final int jjMoveStringLiteralDfa20_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0);
      return 20;
   }
   switch(curChar)
   {
      case 103:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(20, 16, 5);
         break;
      default :
         break;
   }
   return jjStartNfa_0(19, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 7;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                     jjCheckNAdd(6);
                  }
                  else if (curChar == 47)
                  {
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAdd(5);
                  }
                  else if (curChar == 35)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAdd(3);
                  }
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 2:
                  if (curChar != 35)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAdd(3);
                  break;
               case 3:
                  if ((0xfffffffffffffbffL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if (curChar != 47)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAdd(5);
                  break;
               case 5:
                  if ((0x3ff800000000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAdd(5);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAdd(6);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAdd(5);
                  }
                  else if (curChar == 64)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(1);
                  }
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(1);
                  break;
               case 3:
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 4:
               case 5:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAdd(5);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjstateSet[jjnewStateCnt++] = 3;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 7 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\144\145\146\141\165\154\164", 
"\116\117\124\40\116\125\114\114", "\115\125\123\124\40\105\130\111\123\124", 
"\114\117\103\101\114\131\40\125\116\111\121\125\105", "\107\114\117\102\101\114\131\40\125\116\111\121\125\105", 
"\166\141\154\165\145", "\111\156\164\145\147\145\162", "\123\164\162\151\156\147", 
"\103\157\155\160\154\145\170\102\157\157\154\145\141\156", 
"\103\157\155\160\154\145\170\125\156\161\165\157\164\145\144\123\164\162\151\156\147", "\111\156\164\145\147\145\162\101\162\162\141\171", null, null, null, null, 
"\173", "\175", "\42", "\133", "\135", "\73", "\54", "\75", "\56", "\50", "\51", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x1ffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[7];
private final int[] jjstateSet = new int[14];
protected char curChar;
public KesoPropertyManagerReaderTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public KesoPropertyManagerReaderTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 7; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
