/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include "global.h"
#include "c12_String.h"
#include "c13_DebugOut.h"
#include "c3_Task.h"
#include "os.h"
#include "domains.h"
void StartupHook() {
	/* Initialize heaps */
	((irr_listel_t*) keso_epos_d_dom1_heap)->size = 128;
	((irr_listel_t*) keso_epos_d_dom1_heap)->next = (irr_listel_t*) -1;
	((irr_listel_t*) keso_epos_d_dom1_heap)->alloccolor = 0;
	((irr_listel_t*) keso_epos_d_dom1_heap)->mode = 0;

	/* Initialize keso_task_index */
	keso_task_index[keso_epos_d_dom1_t_task1] = (c3_Task_t*) ((object_t*) &keso_epos_d_dom1_t_task1_obj);
	keso_task_index[INVALID_TASK] = NULL;

	/* Call class constructors */
	{
		c12_String_m5__clinit_();
		c13_DebugOut_m3__clinit_();
		c3_Task_m2__clinit_();
	}
	/* Call portal class constructors */

	/* Call each Task's constructor */
	c4_DmecApp_m2__init_((object_t*) keso_task_index[keso_epos_d_dom1_t_task1]);
	keso_task_index[keso_epos_d_dom1_t_task1]->_task_id = keso_epos_d_dom1_t_task1;

}

void PreTaskHook() {
	/* Init keso_curr_task and keso_current_domain_id */
	KESO_TASKCLASSTYPE *ct = keso_curr_task_fkt();
	KESO_SET_CURRENT_TASK(ct);
}

void PostTaskHook() { /* empty PostTaskHook to satisfy ProOSEK */ }

TASK(keso_epos_d_dom1_t_task1) {
	keso_stack_t stack = { .domain_id = 0, .llrefs=KESO_EOLL, .next=NULL };
	keso_stack_index[keso_epos_d_dom1_t_task1] = &stack;
	c4_DmecApp_m1_launch(((object_t*) &keso_epos_d_dom1_t_task1_obj));
	stack.llrefs=NULL;
	keso_stack_index[keso_epos_d_dom1_t_task1] = ((void*)0);
	TerminateTask();
}

