function plot_approximation(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 06-Sep-2011 14:41:29

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
xlim([1 30]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'Marker','o','DisplayName','Scenario-adapted');
set(plot1(2),'Marker','square','DisplayName','Hand-coded');

% Create xlabel
xlabel('Number of components');

% Create ylabel
ylabel('Lines of code');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest','Visible','off');

