/* Generated By:JavaCC: Do not edit this line. KesoParameterReaderConstants.java */
package keso.editor.gui.compilation.parameter.reader;

public interface KesoParameterReaderConstants {

  int EOF = 0;
  int DESCRIPTION = 5;
  int LINECOMMENT = 6;
  int DEFAULTVALUE = 7;
  int DEFSEPARATOR = 8;
  int STRING = 9;
  int BOOLEAN = 10;
  int IDENTIFIER = 11;
  int NUMBER = 12;
  int LETTER = 13;
  int DIGIT = 14;
  int LBRACE = 15;
  int RBRACE = 16;
  int DQUOTE = 17;
  int LBRACKET = 18;
  int RBRACKET = 19;
  int SEMICOLON = 20;
  int COMMA = 21;
  int ASSIGNMENT = 22;
  int DOT = 23;
  int LPAREN = 24;
  int RPAREN = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<DESCRIPTION>",
    "<LINECOMMENT>",
    "\"default value\"",
    "\"separator\"",
    "\"string\"",
    "\"boolean\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\".\"",
    "\"(\"",
    "\")\"",
  };

}
