/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"


/*
 * call analyse 0 c6_StringBuffer_m3_copy_chars
 */
/* java/lang/StringBuffer.copy_chars([CI[CII)V */

void c6_StringBuffer_m3_copy_chars(object_t* obj0,jint i1,object_t* obj2,jint i3,jint i4) {
	jint i5_1;
	jint i6_1;
	jint i7_1;
	jchar c8_1;

	i5_1 = 0x0;
	
c6_StringBuffer_m3_copy_chars_B3: /* Pred:  0 10 No: 2 done */
	
/*==============================================================/
| 273: 		for(int i=0; i<count; i++) dst[dstOffset+i] = src[srcOffset+i];
/==============================================================*/
	/* i5_1 = Phi(0,i5_1)  */;
	if (i5_1>=i4) goto c6_StringBuffer_m3_copy_chars_B28;
	
/* c6_StringBuffer_m3_copy_chars_B10:  Pred:  3 No: 3 done */
	i6_1 = (i3+i5_1);
	i7_1 = (i1+i5_1);
	KESO_CHECK_ARR_REF(obj0,i7_1,"copy_chars",20);
	c8_1 = ((char_array_t*)obj0)->data[i7_1];
	KESO_CHECK_ARR_REF(obj2,i6_1,"copy_chars",21);
	((char_array_t*)obj2)->data[i6_1]=c8_1;
	i5_1 = (i5_1+0x1);
	goto c6_StringBuffer_m3_copy_chars_B3;
	
c6_StringBuffer_m3_copy_chars_B28: /* Pred:  3 No: 4 done */
	
/*==============================================================/
| 274: 	}
/==============================================================*/
	/* goto c6_StringBuffer_m3_copy_chars_B30 */;
	
/* c6_StringBuffer_m3_copy_chars_B30:  Pred:  28 No: 5 done */
	return;
}

