function plot_latency(ymatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 30-Aug-2010 14:40:23

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'YTick',[0 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500],...
    'YGrid','on',...
    'XTick',[1 2 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 2200]);
box('on');
hold('all');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'ShowBaseLine','off','BaseValue',1,'Parent',axes1);
set(bar1(1),'Tag','fg','DisplayName','No CSMA-CA / ACK');
set(bar1(2),'DisplayName','No ACK');
set(bar1(3),'DisplayName','No CSMA-CA');
set(bar1(4),'DisplayName','CSMA-CA/ACK enabled');
set(bar1(5),'DisplayName','CSMA-CA/ACK/beacons enabled');

% Create xlabel
xlabel('Number of hops');

% Create ylabel
ylabel('Time (ms)');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','West');

