/* THIS FILE IS AUTO GENERATED BY KESO! DON'T EDIT */

#include <keso_support.h>
#include <keso_types.h>
#include "global.h"
#include "domains.h"
#include "c6_StringBuffer.h"
#include "char_array.h"
#include "c13_DebugOut.h"


/*
 * call analyse 0 c13_DebugOut_m2_println
 */
/* test/DebugOut.println()V PURE */

void c13_DebugOut_m2_println(void) {
	jint i3_0;
	jint i3_1;
	jint i3_2;
	jint i8_1;
	object_t* obj0_0;
	object_t* obj4_0;
	object_t* obj7_1;
	object_t* obj7_2;

	
/*==============================================================/
| 88: 		StringBuffer b = buf;
| 89: 		b.append('\n');
| 90: 		raw_print(b);
| 91: 		b.setLength(0);
/==============================================================*/
	obj0_0 = ((object_t*)SC13_DEBUGOUT_C13F1_BUF);
	KESO_CHECK_NULLPOINTER(obj0_0,"println",7);
	i3_0 = ((C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length)+0x1);
	c6_StringBuffer_m2_ensureCapacity((object_t*)obj0_0,i3_0);
	obj4_0 = (C6_STRINGBUFFER_OBJ(obj0_0)->c6f1_data);
	i3_1 = (C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length);
	KESO_CHECK_ARR_REF(obj4_0,i3_1,"println",7);
	((char_array_t*)obj4_0)->data[i3_1]=0xa;
	i3_2 = ((C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length)+0x1);
	(C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length) = i3_2;
	c13_DebugOut_m4_raw_print((object_t*)obj0_0);
	c6_StringBuffer_m2_ensureCapacity((object_t*)obj0_0,0x0);
	if (0x0<=(C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length)) goto cc31375837_c6_StringBuffer_m5_setLength_B39;
	
/* cc18945918_c6_StringBuffer_m5_setLength_B13:  Pred:  0 No: 2 done */
	i8_1 = (C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length);
	
cc24745276_c6_StringBuffer_m5_setLength_B18: /* Pred:  13 23 No: 3 done */
	/* i8_1 = Phi(i8_1,i8_1)  */;
	if (i8_1>=0x0) goto cc9649099_c6_StringBuffer_m5_setLength_B36;
	
/* cc30638546_c6_StringBuffer_m5_setLength_B23:  Pred:  18 No: 4 done */
	obj7_1 = (C6_STRINGBUFFER_OBJ(obj0_0)->c6f1_data);
	KESO_CHECK_ARR_REF(obj7_1,i8_1,"println",17);
	((char_array_t*)obj7_1)->data[i8_1]=0x0;
	i8_1 = (i8_1+0x1);
	goto cc24745276_c6_StringBuffer_m5_setLength_B18;
	
cc9649099_c6_StringBuffer_m5_setLength_B36: /* Pred:  18 No: 5 done */
	goto cc24257622_c6_StringBuffer_m5_setLength_B46;
	
cc31375837_c6_StringBuffer_m5_setLength_B39: /* Pred:  0 No: 8 done */
	obj7_2 = (C6_STRINGBUFFER_OBJ(obj0_0)->c6f1_data);
	KESO_CHECK_ARR_REF(obj7_2,0,"println",17);
	((char_array_t*)obj7_2)->data[0x0]=0x0;
	
cc24257622_c6_StringBuffer_m5_setLength_B46: /* Pred:  39 36 No: 6 done */
	
/*==============================================================/
| 92: 	}
/==============================================================*/
	(C6_STRINGBUFFER_OBJ(obj0_0)->c6f2_length) = 0x0;
	/* goto c13_DebugOut_m2_println_B22 */;
	
/* c13_DebugOut_m2_println_B22:  Pred:  46 No: 7 done */
	return;
}

